services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.job-api
    image: soccer-backend:latest
    profiles:
      - backend-only

networks:
  soccer-network:
    external: true
